[General]
# Supported values: atom, rss2, rss1
rssFeedType=atom
rssFeed=https://github.com/RoYoshi/FE-Xico/releases.atom


# Leave a command empty to disable it.
# Any command other than the system update command will also become hidden.
#
# To run a systemd service:
# ./service-as-program.sh your-system.service
[Commands]

# When true, commands may be stopped by closing FE-Xico Updater.
# Set this to false if a configured command cannot safely handle
# being terminated before completion.
allowEarlyExit=true

# FE-Xico system update
systemUpdateCommand=./service-as-program.sh uupd-manual.service

# FE-Xico rollback
# This currently uses the inherited Bazzite rollback helper.
systemRollbackCommand=bazzite-rollback-helper rollback -y


# FE-Xico OS information displayed by the updater is configured in:
# ./KAboutData_OS.json